[package]
name = "jni_macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits", ] }
proc-macro2 = "1.0"
quote = "1.0"
litrs = "0.4"
